### ISSUE TITLE
Note pooping mode 

### ISSUE THREAD

**Issue by Max5254** [Mechanical-Advantage/RobotCode2024#140]
Add a shooter setpoint which shoots the notes over (and maybe under?) our stage in front of the speaker from any legal area near the middle of the field. See the [1st alliance at Waco](https://youtu.be/DplzjEz754M?si=il6-Fzm1kEHuRexk).

## User Stories

- As a driver I want to be able to stockpile notes without needing to aim
- As a referee I want to not call fouls on 6328 for launching notes outside the field
   - Should be avoided:

   https://github.com/Mechanical-Advantage/RobotCode2024/assets/10471019/eecf4299-b5ee-494a-9b79-5034533ab2a9

- As a Chief Delphi user I would like to go to Einstein

**Comment by suryatho** [comment]
Is this the same button as shoot?

**Comment by suryatho** [comment]
super poop
