### ISSUE TITLE
Northstar installation instructions

### ISSUE THREAD

**Issue by rakrakon** [Mechanical-Advantage/RobotCode2024#207]
# Prerequisites:
## Install git:
     sudo apt-get install git
### Verify installation:
      git --version
## Install Docker on ARM64 (Orange PI in our case):
     TODO: put commands for installing docker

## Install Earthly:
     sudo /bin/sh -c 'wget https://github.com/earthly/earthly/releases/latest/download/earthly-linux-amd64 -O /usr/local/bin/earthly && chmod +x /usr/local/bin/earthly && /usr/local/bin/earthly bootstrap --with-autocomplete'
## Verify Installation
     earthly github.com/earthly/hello-world+hello

# Setup:
### Clone the repository:
     git clone https://github.com/rakrakon/NorthStar-Mechanical-Advantage.git
### Verify installation:
     git --version

### Change to the repository directory:
     cd NorthStar-Mechanical-Advantage

### Build the image targeting ARM64:
     earthly +build --platform=linux/arm64

### This will:
- **Use the multi-arch Debian base image**
- **Compile Python from source for ARM64**
- **Install Python packages like NumPy using manylinux wheels**
- **Install dependencies like libjpeg, OpenBLAS**
- **Download and compile OpenCV from source for ARM64**
Building OpenCV takes time. Use earthly builds to monitor progress.

### When complete, verify the image:
     docker images

### Test it:
     docker run -it <image> /bin/bash
This will run OpenCV Python inside the built image.
Replace <image> with the image ID or name.

     python -c "import cv2; print(cv2.__version__)"

**Comment by jwbonner** [comment]
We're a little confused about this issue. We do not support Northstar for other teams' use, and the Earthly build setup is still a work in progress. We don't plan on adding additional documentation for installing Northstar.
