### ISSUE TITLE
Add demo mode(s)

### ISSUE THREAD

**Issue by jwbonner** [Mechanical-Advantage/RobotCode2024#264]
Demo mode capabilities:

- [ ] Dashboard selector for speed limit
  - [ ] Options for competition (100%), fast (70%), medium (30%), and slow (15%)
  - [ ] Scales both linear and angular velocities
- [ ] Dashboard selector for demo shot
  - [ ] Options for competition, short, medium, long, tall (each with appropriate arm/flywheel presets)
  - [ ] If using demo shot, automatically disables super poop and activates shoot align disable & auto flywheel spinup disable (regardless of switch positions)
  - [ ] If using demo shot, aiming automatically shoots without pressing right trigger
- [x] AprilTag demo autos
  - [x] Options for follow or look
- [ ] Option for demo source intake? (Possibly linked to whether a demo shot is selected)
  - [ ] Run flywheels at safer speed with longer delay on sensor, so children can safely feed notes 😇

**Comment by jwbonner** [comment]
Also review trigger changes from Champs and clean up if possible.

**Comment by suryatho** [comment]
Added autos for interacting with demo tag
